// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo_w_gpKQOHR9TGyzw9pENzU5eccYfGgY',
    appId: '1:850859473808:web:c9ff5bf3456baafa039115',
    messagingSenderId: '850859473808',
    projectId: 'erlaapp-de446',
    authDomain: 'erlaapp-de446.firebaseapp.com',
    storageBucket: 'erlaapp-de446.firebasestorage.app',
    measurementId: 'G-VL1B9QS4C8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvFW1E401NM7Fm92VYh_gYK3o1wbPeavg',
    appId: '1:850859473808:android:0f3012989216070c039115',
    messagingSenderId: '850859473808',
    projectId: 'erlaapp-de446',
    storageBucket: 'erlaapp-de446.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA85H2zEXM70xGNFCUnZ1T3wzqbfexC-4w',
    appId: '1:850859473808:ios:a877337b981addb2039115',
    messagingSenderId: '850859473808',
    projectId: 'erlaapp-de446',
    storageBucket: 'erlaapp-de446.firebasestorage.app',
    iosBundleId: 'com.example.hotelHuespedApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA85H2zEXM70xGNFCUnZ1T3wzqbfexC-4w',
    appId: '1:850859473808:ios:a877337b981addb2039115',
    messagingSenderId: '850859473808',
    projectId: 'erlaapp-de446',
    storageBucket: 'erlaapp-de446.firebasestorage.app',
    iosBundleId: 'com.example.hotelHuespedApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo_w_gpKQOHR9TGyzw9pENzU5eccYfGgY',
    appId: '1:850859473808:web:b9867a2d6193b716039115',
    messagingSenderId: '850859473808',
    projectId: 'erlaapp-de446',
    authDomain: 'erlaapp-de446.firebaseapp.com',
    storageBucket: 'erlaapp-de446.firebasestorage.app',
    measurementId: 'G-BMV10024LV',
  );
}
